# Minimal, deterministic Docker build that accepts a single substitution: _IMAGE
# and an optional _FIREBASE_PROJECT_ID used as a build-arg.

substitutions:
  _IMAGE: 'gcr.io/$PROJECT_ID/storyspool-staging:dev'
  _FIREBASE_PROJECT_ID: 'storyspool-be776'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t','$_IMAGE',
      '--build-arg','FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID',
      '.'
    ]

images:
- '$_IMAGE'
