steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/storyspool-staging:latest'
  - '--build-arg'
  - 'FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/storyspool-staging:latest'
