name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for forbidden directories
        run: |
          if [ -d "node_modules" ] || [ -d ".venv" ]; then
            echo "Error: node_modules or .venv directory found. These should not be committed."
            exit 1
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python -m pip install black flake8 pytest
      - run: black --check .
      - run: flake8 .
      - run: pytest -q
