name: deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      REGION: us-central1
      REPO: storyspool
      IMAGE: app
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIP }}
          service_account: ${{ secrets.DEPLOY_SA }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Build & Push
        run: |
          gcloud services enable artifactregistry.googleapis.com run.googleapis.com cloudbuild.googleapis.com
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
          TAG=${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${REPO}/${IMAGE}:${{ github.sha }}
          docker build -t $TAG .
          docker push $TAG
      - name: Deploy
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            SVC=storyspool-staging
            ENV=staging
          else
            SVC=storyspool-prod
            ENV=prod
          fi
          gcloud run deploy $SVC             --image ${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${REPO}/${IMAGE}:${{ github.sha }}             --region $REGION --allow-unauthenticated             --service-account ${{ secrets.DEPLOY_SA }}             --set-env-vars GCP_PROJECT=${{ secrets.GCP_PROJECT }},ENV=$ENV
